<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>ClasificadorIA.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="clasificadoria.ico" />
    <None Remove="clasificadoria.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="clasificadoria.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="clasificadoria.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
