<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyTitle>ClasificadorIA</AssemblyTitle>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Description>Organizador de archivos por categorías con IA</Description>
    <ApplicationIcon>Assets\clasificadoria.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoCloudware.UI.Core\NoCloudware.UI.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*" />
    <Resource Include="Resources\**\*" />
  </ItemGroup>

</Project>